import Database from "better-sqlite3";
import path from "path";
import fs from "fs";

const DB_PATH = "./data/acts.db";
const resolvedPath = path.resolve(DB_PATH);
const dir = path.dirname(resolvedPath);
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

const db = new Database(resolvedPath);
db.pragma("journal_mode = WAL");

// Ensure table exists
db.exec(`
  CREATE TABLE IF NOT EXISTS acts_of_service (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    name            TEXT    NOT NULL,
    email           TEXT    NOT NULL,
    ward_name       TEXT    NOT NULL,
    side_of_veil    TEXT    NOT NULL CHECK(side_of_veil IN ('this', 'other')),
    act_description TEXT    NOT NULL,
    status          TEXT    NOT NULL DEFAULT 'pending' CHECK(status IN ('pending', 'approved')),
    created_at      DATETIME NOT NULL DEFAULT (datetime('now'))
  );
`);

const thisSideActs = [
  "Helped an elderly neighbor carry groceries into their home",
  "Mowed the lawn for a family who just had a new baby",
  "Drove a friend to their doctor's appointment",
  "Made dinner for a family going through a difficult time",
  "Volunteered at the local food bank for a morning shift",
  "Helped a coworker with a project they were struggling with",
  "Picked up litter along the walking trail near our neighborhood",
  "Visited a homebound member and brought them fresh flowers",
  "Helped a teenager practice for their job interview",
  "Shoveled snow from three neighbors' driveways after the storm",
  "Wrote thank-you notes to all the teachers at our local school",
  "Organized a clothing drive for families in need",
  "Babysat for a single mom so she could have an evening out",
  "Helped a refugee family navigate the grocery store",
  "Read stories to children at the local library",
  "Fixed a leaky faucet for an elderly widow in the ward",
  "Brought homemade cookies to the fire station",
  "Helped a neighbor move into their new apartment",
  "Tutored a student struggling with math after school",
  "Donated blood at the community blood drive",
  "Walked a neighbor's dog while they were recovering from surgery",
  "Helped paint the community center meeting room",
  "Drove an elderly couple to their grandchild's recital",
  "Organized a neighborhood cleanup day",
  "Made care packages for the homeless shelter",
  "Helped a friend build a wheelchair ramp for their mother",
  "Volunteered to coach the youth soccer team",
  "Prepared meals for the missionaries serving in our area",
  "Helped a young couple budget and plan their finances",
  "Set up chairs and cleaned up after the ward activity",
  "Gave a ride to someone whose car broke down",
  "Mentored a young adult starting their first job",
  "Knitted blankets for the NICU at the hospital",
  "Helped an immigrant neighbor practice English",
  "Organized a carpool for elderly members to attend the temple",
  "Cleaned the church building on a Saturday morning",
  "Brought soup to a sick neighbor and their family",
  "Helped a widower learn to cook simple meals",
  "Volunteered at the Special Olympics event",
  "Repaired a broken fence for a neighbor who couldn't afford it",
  "Drove meals to homebound seniors three times this week",
  "Helped a teen prepare their college application essays",
  "Organized a gratitude wall at the community center",
  "Spent an afternoon weeding a neighbor's garden",
  "Taught a free cooking class for young adults in the ward",
  "Helped set up and serve at the community Thanksgiving dinner",
  "Visited patients at the hospital who had no family nearby",
  "Assembled furniture for a family who just moved in",
  "Helped a neighbor file their taxes for free",
  "Organized a book exchange for the neighborhood",
  "Drove a teenager to early-morning seminary every day this month",
  "Helped install a car seat for a new parent",
  "Wrote encouraging letters to soldiers overseas",
  "Volunteered as a crossing guard at the elementary school",
  "Helped a neighbor troubleshoot their computer problems",
  "Made welcome baskets for new families moving into the ward",
  "Spent the afternoon cleaning up after a neighborhood flood",
  "Took family photos for a family who couldn't afford a photographer",
  "Babysat during a funeral so parents could attend",
  "Helped a disabled veteran with yard work every Saturday",
  "Organized a warm clothing collection before winter",
  "Taught a neighbor's child to ride a bike",
  "Helped translate documents for a non-English speaking family",
  "Hosted a dinner for new members of the ward",
  "Ran errands for a mother on bed rest during her pregnancy",
  "Helped build beds for children who were sleeping on the floor",
  "Organized a community garden project",
  "Fixed a neighbor's broken porch steps",
  "Stayed late to help clean up after the youth dance",
  "Made breakfast burritos for the construction workers next door",
  "Helped a young family winterize their home",
  "Drove a friend to the airport at 4am without complaint",
  "Volunteered at the crisis hotline",
  "Helped a struggling student with their science fair project",
  "Organized a surprise birthday party for a lonely neighbor",
  "Walked with an anxious friend every morning for a month",
  "Helped a family pack up their home after a sudden job transfer",
  "Set up a Little Free Library in our neighborhood",
  "Repaired toys and bikes for a children's charity",
  "Helped a neighbor's teenager with their driving practice",
  "Volunteered at the animal shelter walking dogs",
  "Organized a meal train for a family with a sick child",
  "Helped clean and organize the church supply closet",
  "Made homemade jam and gave jars to every neighbor on the street",
  "Taught an elderly member how to video call their grandchildren",
  "Spent a Saturday helping Habitat for Humanity build a house",
  "Helped a neighbor drain and clean their flooded basement",
  "Gave music lessons to a child whose family couldn't afford them",
  "Wrote and delivered encouraging notes to every home on our block",
  "Volunteered as a reading buddy at the elementary school",
  "Helped a widow sort through her late husband's belongings",
  "Organized a fun run fundraiser for the children's hospital",
  "Made freezer meals for a family going through chemotherapy",
  "Helped a young mother with her laundry when she was overwhelmed",
  "Spent an afternoon assembling bikes for a holiday toy drive",
  "Helped a newly single dad learn to braid his daughter's hair",
  "Planted trees along the community walking path",
  "Drove a neighbor to physical therapy three times a week",
  "Organized a neighborhood watch program",
  "Helped a friend move their elderly parent into assisted living",
  "Made quilts for foster children entering new homes",
  "Volunteered to translate at parent-teacher conferences",
  "Helped a family set up a memorial for their loved one",
  "Cleaned and detailed a single mom's car as a surprise",
  "Organized a community potluck for National Night Out",
  "Helped a friend process and preserve their garden harvest",
  "Taught basic car maintenance to teenagers in the ward",
  "Set up a study group for youth preparing for college entrance exams",
  "Helped a neighbor install new smoke detectors in their home",
  "Volunteered at the soup kitchen every Friday this month",
  "Made care baskets for new mothers in the ward",
  "Helped an elderly couple declutter and organize their garage",
  "Drove a vanload of donations to the disaster relief center",
  "Helped a neighbor's child overcome their fear of swimming",
  "Organized a pen pal program between youth and nursing home residents",
  "Fixed the plumbing in a single mother's bathroom for free",
  "Made and delivered Valentines to every resident at the care center",
  "Helped a family create an emergency preparedness kit",
  "Taught a free yoga class at the community center",
  "Helped a neighbor childproof their home for a new grandchild",
  "Organized a community talent show to raise funds for scouts",
  "Volunteered to be a mentor for a youth aging out of foster care",
  "Helped a family create a budget after a job loss",
  "Made sandwiches and distributed them to people living on the streets",
  "Spent the day helping a neighbor reroof their shed",
  "Organized a holiday gift exchange for families in need",
  "Helped a friend move their piano to their new house",
  "Volunteered to staff the ward's emergency preparedness fair",
  "Made hand-sewn masks during flu season for immuno-compromised neighbors",
  "Helped paint a mural at the youth center",
  "Organized a community blood drive at the church",
  "Spent Saturday mornings coaching a youth basketball team",
  "Helped a neighbor set up their new garden irrigation system",
  "Delivered prescriptions to elderly neighbors who can't drive",
  "Organized a ward campout and planned all the activities",
  "Helped a family write and mail their Christmas cards",
  "Volunteered as a homework helper at the after-school program",
  "Helped a friend landscape their yard before a family reunion",
  "Made and delivered chicken soup to five sick families this winter",
  "Taught a free photography workshop for teens",
  "Helped a neighbor patch drywall after a plumbing leak",
  "Organized a community Easter egg hunt for all the neighborhood kids",
  "Drove an elderly member to visit their spouse's grave on their anniversary",
  "Helped a friend clear brush and create a firebreak around their property",
  "Volunteered to lead a grief support group at the church",
  "Made personalized bookmarks for every child in Primary",
  "Helped a family build raised garden beds in their backyard",
  "Organized a teddy bear drive for children in the ER",
  "Helped a neighbor replace their broken mailbox",
  "Spent an afternoon teaching a friend to sew",
  "Volunteered at the school carnival running the ring toss booth",
  "Helped a single dad put together his kids' birthday party",
  "Made blessing bags with snacks and supplies for people in need",
  "Helped a neighbor find and apply for assistance programs",
  "Organized a ward service auction to raise funds for a family in crisis",
  "Taught CPR and first aid to the youth group",
  "Helped a friend deep clean their house before hosting Thanksgiving",
  "Volunteered at the community garden teaching children about plants",
  "Made holiday decorations for the nursing home common areas",
  "Helped a family assemble a swing set in their backyard",
  "Organized a coat drive and collected over 200 coats",
  "Helped an elderly neighbor sort and organize their medications",
  "Spent a morning pulling weeds at the community memorial garden",
  "Made and delivered birthday cakes to children at the shelter",
  "Helped a neighbor's teen prepare for their Eagle Scout project",
  "Organized a neighborhood garage sale with proceeds going to charity",
  "Volunteered at the Red Cross during the local flooding",
  "Helped a friend recover photos from their damaged hard drive",
  "Made friendship bracelets with nursing home residents",
  "Helped a family install a handrail on their front porch steps",
  "Organized a back-to-school supply drive for underprivileged kids",
  "Taught an elderly neighbor how to use their new smartphone",
];

const otherSideActs = [
  "Did family history research and found 12 new ancestors",
  "Performed baptisms for the dead at the temple",
  "Indexed 500 historical records for FamilySearch",
  "Submitted names for temple ordinances that had been waiting years",
  "Spent the day doing initiatory work at the temple",
  "Helped a friend learn to navigate FamilySearch for the first time",
  "Completed endowment work for three ancestors",
  "Scanned and uploaded old family photos to FamilySearch Memories",
  "Researched and documented stories of ancestors for family records",
  "Organized a ward temple day and arranged rides for everyone",
  "Transcribed old family letters to preserve ancestor stories",
  "Performed sealings for a family line going back five generations",
  "Helped an elderly member submit their family names for temple work",
  "Attended the temple weekly for three months doing ordinance work",
  "Researched military records to find information about ancestors who served",
  "Created a family history book for a reunion gathering",
  "Helped translate foreign-language records for indexing",
  "Performed confirmations for the dead at the temple",
  "Taught a family history class to help others get started",
  "Found and connected with distant cousins to share family records",
  "Digitized old family VHS tapes and added them to Memories",
  "Did proxy temple work for a friend's ancestors",
  "Organized a family history center night at the church",
  "Helped a new member learn about family history and temple work",
  "Indexed census records from the early 1900s for FamilySearch",
  "Spent a Saturday at the temple doing endowments for ancestors",
  "Recorded oral histories from elderly family members",
  "Resolved duplicate records on FamilySearch for my family tree",
  "Performed temple ordinances for victims of a historical tragedy",
  "Helped a teenager complete their first family history project",
  "Researched parish records from Europe to extend our family line",
  "Did initiatory work at the temple for an entire morning",
  "Compiled a family cookbook with recipes from deceased relatives",
  "Attended the temple twice this week to do ordinance work",
  "Volunteered at the family history center helping patrons research",
  "Found birth records for ancestors who immigrated from overseas",
  "Performed proxy baptisms for names submitted by ward members",
  "Created a detailed family tree poster for the family reunion",
  "Helped index Civil War records to make them searchable",
  "Visited ancestral homelands and gathered records and photos",
  "Did endowment work for 10 ancestors in a single temple session",
  "Transcribed old diary entries from a great-grandmother",
  "Organized a youth temple trip and helped them prepare names",
  "Researched and documented the immigration story of our family",
  "Performed sealings at the temple for a newly discovered family line",
  "Helped a neighbor upload their genealogy files to FamilySearch",
  "Indexed hospital birth records from the 1800s",
  "Completed all ordinances for an ancestor found during research",
  "Wrote biographies for ancestors using historical records",
  "Spent the morning doing confirmations at the temple",
  "Helped correct errors in the family tree on FamilySearch",
  "Did proxy baptisms for 15 names at the temple this week",
  "Preserved fragile family documents by scanning and archiving them",
  "Taught youth how to find their own family names for the temple",
  "Researched newspaper archives for obituaries of ancestors",
  "Performed endowment work for ancestors from the 1700s",
  "Organized all the family history records into a shared drive",
  "Attended the temple three times this month for ordinance work",
  "Helped a friend untangle a complicated family line on FamilySearch",
  "Transcribed passenger ship manifests for indexing",
  "Did initiatory and endowment work back-to-back at the temple",
  "Created a memory page on FamilySearch for a recently deceased friend",
  "Indexed land records to help others find their ancestors",
  "Performed sealings for five couples from my family line",
  "Researched and documented stories of pioneer ancestors",
  "Helped ward members prepare family names before the temple trip",
  "Spent a week focused on family history research each evening",
  "Found and verified birth, marriage, and death records for a family line",
  "Did proxy baptisms and confirmations for names found by a friend",
  "Organized family photos by generation and added names and dates",
  "Taught a family history workshop at the ward activity night",
  "Researched ancestors from a small village using church records",
  "Performed all temple ordinances for a line of seven ancestors",
  "Volunteered to help with the FamilySearch indexing initiative",
  "Helped elderly members print and organize their family trees",
  "Did endowment work at the temple every Saturday this month",
  "Scanned and preserved a collection of handwritten family letters",
  "Connected family stories to historical events for a family history",
  "Attended the temple on behalf of ancestors from five generations back",
  "Helped a youth find their four-generation family chart for camp",
  "Indexed church records from South America",
  "Performed proxy ordinances for ancestors discovered during a DNA match",
  "Documented and preserved family heirlooms with photos and descriptions",
  "Organized a family history fireside and invited a guest speaker",
  "Spent the afternoon doing sealings at the temple",
  "Researched and added sources to ancestor profiles on FamilySearch",
  "Did temple work for ancestors who crossed the plains as pioneers",
  "Helped a friend research their Native American heritage",
  "Indexed African American genealogy records for the Freedmen's Bureau",
  "Created video memorials for deceased family members",
  "Performed endowments for ancestors from my mother's side of the family",
  "Transcribed and translated German records for family history",
  "Attended the temple for a special session focused on family names",
  "Helped a ward member prepare 50 names for temple submission",
  "Researched wills and probate records to find family connections",
  "Did proxy baptisms for names that had been waiting over 100 years",
  "Created a digital family history scrapbook with photos and stories",
  "Spent a Saturday morning doing initiatory work at the temple",
  "Found and documented the burial sites of ancestors",
  "Helped a family reconnect with relatives through genealogy research",
  "Indexed immigration records from Ellis Island",
  "Performed temple ordinances for ancestors found through DNA research",
  "Organized a family history potluck where everyone shared stories",
  "Transcribed audio recordings of grandparents telling family stories",
  "Did endowment work for ancestors who lived during the Revolutionary War",
  "Helped ward youth learn to use FamilySearch for Duty to God",
  "Researched and corrected dates on the family tree using original documents",
  "Performed sealings at the temple for three families from my line",
  "Preserved old photo albums by digitizing and organizing the images",
  "Taught a class on how to use DNA results for family history",
  "Spent the week preparing 30 names for an upcoming temple visit",
  "Indexed marriage records from the 1800s for FamilySearch",
  "Did proxy confirmations for names submitted by several ward families",
  "Created a timeline of family history events spanning 200 years",
  "Attended the temple with my family and did ordinances together",
  "Helped a non-member friend trace their family history",
  "Researched and preserved the history of our family's old homestead",
  "Performed initiatory and endowment work for my grandmother's line",
  "Volunteered at the family history library helping visitors",
  "Found new family connections through a genealogy DNA test",
  "Submitted 40 names for temple ordinances this month",
  "Documented family traditions passed down through generations",
  "Did temple work for ancestors found in newly released records",
  "Organized a family reunion focused on sharing family history",
  "Transcribed and preserved recipes written by deceased relatives",
  "Performed proxy baptisms at the temple every week this month",
  "Helped a friend research their Scandinavian family history",
  "Indexed vital records to help others discover their ancestry",
  "Completed all ordinances for a family line of 20 ancestors",
  "Recorded the life story of an elderly ward member for their family",
  "Did endowment work for ancestors from the 1600s discovered in parish records",
  "Helped organize the ward's family history resources and library",
  "Performed sealings for a newly discovered branch of the family",
  "Researched and documented the history of ancestral hometowns",
  "Attended a family history conference and shared what I learned",
  "Created FamilySearch profiles for 25 ancestors missing from the tree",
  "Did proxy ordinances at the temple twice this week",
  "Helped a youth prepare their family history for a school project",
  "Indexed records from archives in Eastern Europe",
  "Found and preserved old letters between ancestors during wartime",
  "Performed temple work for ancestors who survived a famine",
  "Compiled a photo directory of ancestors going back seven generations",
  "Helped ward members resolve hints and suggestions on FamilySearch",
  "Spent the day at the temple performing all available ordinances",
  "Researched and wrote up the story of how ancestors joined the church",
  "Digitized a family Bible with handwritten genealogical records",
  "Organized a temple excursion for the Relief Society",
  "Performed proxy baptisms for names gathered at a family reunion",
  "Helped a neighbor create a legacy video for their family",
  "Indexed thousands of records as part of a ward indexing challenge",
  "Did initiatory work for ancestors from my father's line",
  "Compiled a book of remembrance for our extended family",
  "Performed endowments for ancestors discovered through new research",
  "Helped a young couple start their family history journey",
  "Researched court records to piece together an ancestor's life story",
  "Attended the temple monthly for the past year doing family names",
  "Found and connected with a living relative through FamilySearch",
  "Indexed old tax records to help trace family property ownership",
  "Performed sealings for ancestors going back to the 1500s",
  "Preserved and shared family stories in a private family blog",
  "Helped a new convert prepare their first family names for the temple",
  "Did proxy baptisms and confirmations for 20 ancestors this month",
  "Organized a family history display at the ward open house",
  "Transcribed old school records that mentioned ancestors",
  "Performed temple ordinances for ancestors from three different countries",
  "Volunteered at the family history center teaching basic research skills",
  "Created a memory book for a family who lost a loved one",
  "Researched and documented military service of ancestors in both World Wars",
  "Did endowment work at the temple for newly submitted family names",
  "Helped a senior couple navigate the FamilySearch mobile app",
  "Indexed church christening records from the 1700s",
  "Performed proxy ordinances for ancestors of a friend who passed away",
  "Compiled ancestor stories into a family newsletter",
  "Attended the temple for an early morning endowment session",
  "Helped a teenager earn their family history merit badge",
  "Researched and shared the stories of women ancestors often overlooked",
  "Performed sealings at the temple and felt a deep connection to my heritage",
  "Preserved handwritten letters between grandparents during their courtship",
  "Organized a family history night for young single adults",
  "Did proxy baptisms for names that had been in the system for decades",
  "Created a visual family tree display for the family reunion",
  "Helped a widow complete temple work for her late husband's family",
  "Indexed vital records from newly digitized archives",
  "Researched land grants to trace ancestors' westward migration",
  "Performed all available temple ordinances for a line of 15 ancestors",
  "Digitized and transcribed an ancestor's personal journal",
  "Spent the afternoon at the temple doing initiatory work for family names",
  "Helped a missionary prepare family names to take to the temple",
  "Found and documented ancestor graves in three different states",
  "Organized a family history seminar at the stake center",
  "Performed proxy endowments for ancestors from Scandinavia",
  "Transcribed and preserved a collection of family poems and hymns",
  "Attended the temple with family names prepared by my children",
  "Helped a recently reactivated member begin their family history work",
  "Indexed parish records from Ireland to help trace family roots",
  "Compiled a comprehensive family medical history from genealogical records",
  "Did temple ordinances for ancestors connected through a DNA match surprise",
];

const firstNames = [
  "James", "Mary", "Robert", "Patricia", "John", "Jennifer", "Michael", "Linda",
  "David", "Elizabeth", "William", "Barbara", "Richard", "Susan", "Joseph", "Jessica",
  "Thomas", "Sarah", "Christopher", "Karen", "Charles", "Lisa", "Daniel", "Nancy",
  "Matthew", "Betty", "Anthony", "Margaret", "Mark", "Sandra", "Donald", "Ashley",
  "Steven", "Kimberly", "Paul", "Emily", "Andrew", "Donna", "Joshua", "Michelle",
  "Kenneth", "Carol", "Kevin", "Amanda", "Brian", "Dorothy", "George", "Melissa",
  "Timothy", "Deborah", "Ronald", "Stephanie", "Edward", "Rebecca", "Jason", "Sharon",
  "Jeffrey", "Laura", "Ryan", "Cynthia", "Jacob", "Kathleen", "Gary", "Amy",
  "Nicholas", "Angela", "Eric", "Shirley", "Jonathan", "Anna", "Stephen", "Brenda",
  "Larry", "Pamela", "Justin", "Emma", "Scott", "Nicole", "Brandon", "Helen",
  "Benjamin", "Samantha", "Samuel", "Katherine", "Raymond", "Christine", "Gregory", "Debra",
  "Frank", "Rachel", "Alexander", "Carolyn", "Patrick", "Janet", "Jack", "Catherine",
];

const lastNames = [
  "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis",
  "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson",
  "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson",
  "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson", "Walker",
  "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill",
  "Flores", "Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell",
  "Mitchell", "Carter", "Roberts",
];

const wards = [
  "Maple Grove", "Cedar Hills", "Riverside", "Mountain View", "Sunridge",
  "Oakwood", "Pleasant Valley", "Lakeside", "Heritage Park", "Eagle Rock",
  "Willow Creek", "Pine Meadows", "Valley View", "Spring Creek", "Harvest Hills",
];

function randomItem(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

const insert = db.prepare(`
  INSERT INTO acts_of_service (name, email, ward_name, side_of_veil, act_description, status, created_at)
  VALUES (?, ?, ?, ?, ?, 'approved', datetime('now', '-' || ? || ' hours'))
`);

const insertMany = db.transaction(() => {
  // 175 acts on THIS side
  for (let i = 0; i < 175; i++) {
    const first = randomItem(firstNames);
    const last = randomItem(lastNames);
    const ward = randomItem(wards);
    const desc = thisSideActs[i % thisSideActs.length];
    const hoursAgo = Math.floor(Math.random() * 720); // spread over 30 days
    insert.run(`${first} ${last}`, `${first.toLowerCase()}.${last.toLowerCase()}@email.com`, ward, "this", desc, hoursAgo);
  }

  // 325 acts on OTHER side
  for (let i = 0; i < 325; i++) {
    const first = randomItem(firstNames);
    const last = randomItem(lastNames);
    const ward = randomItem(wards);
    const desc = otherSideActs[i % otherSideActs.length];
    const hoursAgo = Math.floor(Math.random() * 720);
    insert.run(`${first} ${last}`, `${first.toLowerCase()}.${last.toLowerCase()}@email.com`, ward, "other", desc, hoursAgo);
  }
});

insertMany();

// Verify
const counts = db.prepare(`
  SELECT side_of_veil, COUNT(*) as count
  FROM acts_of_service
  WHERE status = 'approved'
  GROUP BY side_of_veil
`).all();

console.log("Seed complete!");
console.log("Counts:", JSON.stringify(counts, null, 2));

const total = db.prepare("SELECT COUNT(*) as total FROM acts_of_service").get();
console.log("Total records:", total.total);

db.close();
